import NavBar from "./components/navBar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "./components/footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "400"] });

export const metadata = {
  title: "Create Travel App",
  description: "Generated by Matias Gigena",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            Height: "100vh",
          }}
        >
          <NavBar />

          <video
            src="/VideoDef.mp4"
            autoPlay
            muted
            loop
            className="w-full h-[100vh] object-cover"
          ></video>

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
